spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.0.100:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    sentinel:
      master: mymaster
      nodes: 192.168.0.100:26379,192.168.0.100:26380,192.168.0.100:26381
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-handlers-package: com.jascola.welcome.web.handler

pagehelper:
  offset-as-page-num: true