spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://10.24.19.100:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    sentinel:
      master: mymaster
      nodes: 10.24.19.100:26379,10.24.19.100:26380,10.24.19.100:26381
    timeout: 6000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-handlers-package: com.jascola.welcome.web.handler

pagehelper:
  offset-as-page-num: true

zookeeper:
  server-addr: 10.24.19.100:2181,10.24.19.100:2182,10.24.19.100:2183

logging:
  pattern:
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} %contextName [%thread] %-5level %logger{36} - %msg%n'
    rolling-file-name: '/usr/local/tomcat/logs/logback.%d{yyyy-MM-dd}.log'
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} %contextName [%thread] %-5level %logger{36} - %msg%n'
    level: info
