version: '3.8'
services:
  redis-master:
    container_name: redis_6379
    image: redis
    command : redis-server /etc/redis/redis.conf
    volumes:
       - /file/docker/redis/redis-node1.conf:/etc/redis/redis.conf
    ports:
       - "6379:6379"
    restart: always

  redis-salve1:
    container_name: redis_6380
    image: redis
    command : redis-server /etc/redis/redis.conf
    volumes:
       - /file/docker/redis/redis-node2.conf:/etc/redis/redis.conf
    ports:
       - "6380:6379"
    restart: always
    depends_on:
       - redis-master

  redis-salve2:
    container_name: redis_6381
    image: redis
    command : redis-server /etc/redis/redis.conf
    volumes:
       - /file/docker/redis/redis-node3.conf:/etc/redis/redis.conf
    ports:
       - "6381:6379"
    restart: always
    depends_on:
       - redis-master

  redis-sentinel-1:
    container_name: sentine-1
    image: redis
    command : redis-sentinel /data/sentinel.conf
    volumes:
       - /file/docker/redis/sentinel-1.conf:/data/sentinel.conf
    ports:
       - "26379:26379"
    restart: always
    depends_on:
       - redis-master


  redis-sentinel-2:
    container_name: sentine-2
    image: redis
    command : redis-sentinel /data/sentinel.conf
    volumes:
       - /file/docker/redis/sentinel-2.conf:/data/sentinel.conf
    ports:
       - "26380:26379"
    restart: always
    depends_on:
       - redis-master

  redis-sentinel-3:
    container_name: sentine-3
    image: redis
    command : redis-sentinel /data/sentinel.conf
    volumes:
       - /file/docker/redis/sentinel-3.conf:/data/sentinel.conf
    ports:
       - "26381:26379"
    restart: always
    depends_on:
       - redis-master


  mysql:
    container_name: mysql
    image: mysql
    ports:
       - "3306:3306"
    restart: always
    environment:
       - MYSQL_ROOT_PASSWORD=123456
    depends_on:
       - redis-master

  tomcat:
    container_name: tomcat
    image: tomcat
    volumes:
       - /file/docker/webapps.bak:/usr/local/tomcat/webapps/
    ports:
       - "8080:8080"
    restart: always
    depends_on:
       - redis-master
