version: '3.8'
services:
  redis-master:
    container_name: redis_6379
    image: redis
    command : redis-server /etc/redis/redis.conf
    hostname : redis-master
    volumes:
       - /file/docker/redis/redis-node1.conf:/etc/redis/redis.conf
    ports:
       - "6379:6379"
    restart: always

  redis-salve1:
    container_name: redis_6380
    image: redis
    command : redis-server /etc/redis/redis.conf
    volumes:
       - /file/docker/redis/redis-node2.conf:/etc/redis/redis.conf
    ports:
       - "6380:6379"
    restart: always


  redis-salve2:
    container_name: redis_6381
    image: redis
    command : redis-server /etc/redis/redis.conf
    volumes:
       - /file/docker/redis/redis-node3.conf:/etc/redis/redis.conf
    ports:
       - "6381:6379"
    restart: always


  redis-sentinel-1:
    container_name: sentine-1
    image: redis
    command : redis-sentinel /data/sentinel.conf
    volumes:
       - /file/docker/redis/sentinel-1.conf:/data/sentinel.conf
    ports:
       - "26379:26379"
    restart: always

  redis-sentinel-2:
    container_name: sentine-2
    image: redis
    command : redis-sentinel /data/sentinel.conf
    volumes:
       - /file/docker/redis/sentinel-2.conf:/data/sentinel.conf
    ports:
       - "26380:26379"
    restart: always


  redis-sentinel-3:
    container_name: sentine-3
    image: redis
    command : redis-sentinel /data/sentinel.conf
    volumes:
       - /file/docker/redis/sentinel-3.conf:/data/sentinel.conf
    ports:
       - "26381:26379"
    restart: always


  mysql:
    container_name: mysql
    image: mysql
    ports:
       - "3306:3306"
    restart: always
    environment:
       - MYSQL_ROOT_PASSWORD=123456

  tomcat:
    container_name: tomcat
    image: tomcat
    volumes:
       - /file/docker/webapps.bak:/usr/local/tomcat/webapps/
    ports:
       - "8080:8080"
    restart: always

  zoo1:
    image: zookeeper:3.4.14
    restart: always
    hostname: zoo1
    ports:
       - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888

  zoo2:
    image: zookeeper:3.4.14
    restart: always
    hostname: zoo2
    ports:
        - "2182:2181"
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888

  zoo3:
    image: zookeeper:3.4.14
    restart: always
    hostname: zoo3
    ports:
        - "2183:2181"
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
